language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm i -D
  - cd ./test/smoke/template
  - npm i -D
  - cd ../../../

scripts:
  - npm test
